### ISSUE TITLE
Thermal Issue with Mk4 Service bay?

### ISSUE THREAD

**Issue by Cabin2N** [ChrisAdderley/MkIVSystem#15] opened 2016-01-23 01:27 UTC
When trying to reenter a shuttle my Vulture kept over heating when connected to the service bay. see attached 
http://steamcommunity.com/sharedfiles/filedetails/?id=606372361
http://steamcommunity.com/sharedfiles/filedetails/?id=606372395
http://steamcommunity.com/sharedfiles/filedetails/?id=606372419

http://steamcommunity.com/sharedfiles/filedetails/?id=606372409

**Comment by ChrisAdderley** [comment] 2016-01-27 01:07
I need more information - from the screenshots that looks like expected behaviour, the cockpit getting warmer on reentry.

**Comment by Cabin2N** [comment] 2016-02-04 23:41
Sorry I will try and be more clear. When I had a vulture cockpit connected to a service bay the cockpit would always overheat and explode during reentry. When I removed the service bay the shuttle reentered without a overheating issue. One thing I noticed was that the service bay was cooler than the cockpit and the hanger. This is just a guess, but I think that the service bay is not conducting heat from neighboring parts.

**Comment by BararQ** [comment] 2018-03-10 10:02
GameData\MarkIVSystem\Parts\Fuselage
mk4servicebay-1.cfg
missiveConstant = 0.87  missing the e, should be emissiveConstant = 0.87 

This sound like what this parameter is suppose to do, I checked this in the 2.4.1 version.

This part is also missing it.
GameData\MarkIVSystem\Parts\Pods\mk4drone-1
mk4drone-1.cfg
missiveConstant = 0.87 missing the e, should be emissiveConstant = 0.87

**Comment by ChrisAdderley** [comment] 2024-10-24 18:06
Fixed in latest release

**Closed as completed by ChrisAdderley** 2024-10-24 18:06 UTC
